### ISSUE TITLE
gtmOnSuccess/gtmOnFailure with async injectScript 

### ISSUE THREAD

**Issue by rush1818** [mbaersch/github-loader-tag#1]
Hello,

While reviewing your template we noticed that the call to `gtmOnSuccess`/`gtmOnFailure` is synchronous in the template execution and doesn't wait for the actual injectScript callbacks to complete. This will incorrectly report tag success/failure state. Specifically [these lines](https://github.com/mbaersch/github-loader-tag/blob/7ee8ab5aa29d4f15b03d4cbbd8c6b6b66fdd4bf6/template.tpl#L104-L119)

**Comment by mbaersch** [comment]
Hi @rush1818,

thanks for checking and letting me know about the problem here! This will surely not be the last time I fall into the async trap :|. Just changed the code to recursively iterate though all URLs and log results and invoke callbacks afterwards. Seems to work as expected now. SHA is updated already for the initial release. Let me know if there are any other issues. 

Thanks, 

best
Markus
